In [31]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import matplotlib
from matplotlib import pyplot as plt

In [32]:
df=pd.read_csv("titanic.csv")
print(df.to_string())

     PassengerId  Survived  Pclass                                                                                Name     Sex    Age  SibSp  Parch              Ticket      Fare            Cabin Embarked
0              1         0       3                                                             Braund, Mr. Owen Harris    male  22.00      1      0           A/5 21171    7.2500              NaN        S
1              2         1       1                                 Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.00      1      0            PC 17599   71.2833              C85        C
2              3         1       3                                                              Heikkinen, Miss. Laina  female  26.00      0      0    STON/O2. 3101282    7.9250              NaN        S
3              4         1       1                                        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00      1      0              113803   53.1000             C123        S
4              5         0       3                                                            Allen, Mr. William Henry    male  35.00      0      0              373450    8.0500              NaN        S
5              6         0       3                                                                    Moran, Mr. James    male    NaN      0      0              330877    8.4583              NaN        Q
6              7         0       1                                                             McCarthy, Mr. Timothy J    male  54.00      0      0               17463   51.8625              E46        S
7              8         0       3                                                      Palsson, Master. Gosta Leonard    male   2.00      3      1              349909   21.0750              NaN        S
8              9         1       3                                   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.00      0      2              347742   11.1333              NaN        S
9             10         1       2                                                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.00      1      0              237736   30.0708              NaN        C
10            11         1       3                                                     Sandstrom, Miss. Marguerite Rut  female   4.00      1      1             PP 9549   16.7000               G6        S
11            12         1       1                                                            Bonnell, Miss. Elizabeth  female  58.00      0      0              113783   26.5500             C103        S
12            13         0       3                                                      Saundercock, Mr. William Henry    male  20.00      0      0           A/5. 2151    8.0500              NaN        S
13            14         0       3                                                         Andersson, Mr. Anders Johan    male  39.00      1      5              347082   31.2750              NaN        S
14            15         0       3                                                Vestrom, Miss. Hulda Amanda Adolfina  female  14.00      0      0              350406    7.8542              NaN        S
15            16         1       2                                                    Hewlett, Mrs. (Mary D Kingcome)   female  55.00      0      0              248706   16.0000              NaN        S
16            17         0       3                                                                Rice, Master. Eugene    male   2.00      4      1              382652   29.1250              NaN        Q
17            18         1       2                                                        Williams, Mr. Charles Eugene    male    NaN      0      0              244373   13.0000              NaN        S
18            19         0       3                             Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)  female  31.00      1      0              345763   18.0000              NaN        S
19            20         1       3                                                             Masselmani, Mrs. Fatima  female    NaN      0      0                2649    7.2250              NaN        C
20            21         0       2                                                                Fynney, Mr. Joseph J    male  35.00      0      0              239865   26.0000              NaN        S
21            22         1       2                                                               Beesley, Mr. Lawrence    male  34.00      0      0              248698   13.0000              D56        S
22            23         1       3                                                         McGowan, Miss. Anna "Annie"  female  15.00      0      0              330923    8.0292              NaN        Q
23            24         1       1                                                        Sloper, Mr. William Thompson    male  28.00      0      0              113788   35.5000               A6        S
24            25         0       3                                                       Palsson, Miss. Torborg Danira  female   8.00      3      1              349909   21.0750              NaN        S
25            26         1       3                           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)  female  38.00      1      5              347077   31.3875              NaN        S
26            27         0       3                                                             Emir, Mr. Farred Chehab    male    NaN      0      0                2631    7.2250              NaN        C
27            28         0       1                                                      Fortune, Mr. Charles Alexander    male  19.00      3      2               19950  263.0000      C23 C25 C27        S
28            29         1       3                                                       O'Dwyer, Miss. Ellen "Nellie"  female    NaN      0      0              330959    7.8792              NaN        Q
29            30         0       3                                                                 Todoroff, Mr. Lalio    male    NaN      0      0              349216    7.8958              NaN        S
30            31         0       1                                                            Uruchurtu, Don. Manuel E    male  40.00      0      0            PC 17601   27.7208              NaN        C
31            32         1       1                                      Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1      0            PC 17569  146.5208              B78        C
32            33         1       3                                                            Glynn, Miss. Mary Agatha  female    NaN      0      0              335677    7.7500              NaN        Q
33            34         0       2                                                               Wheadon, Mr. Edward H    male  66.00      0      0          C.A. 24579   10.5000              NaN        S
34            35         0       1                                                             Meyer, Mr. Edgar Joseph    male  28.00      1      0            PC 17604   82.1708              NaN        C
35            36         0       1                                                      Holverson, Mr. Alexander Oskar    male  42.00      1      0              113789   52.0000              NaN        S
36            37         1       3                                                                    Mamee, Mr. Hanna    male    NaN      0      0                2677    7.2292              NaN        C
37            38         0       3                                                            Cann, Mr. Ernest Charles    male  21.00      0      0          A./5. 2152    8.0500              NaN        S
38            39         0       3                                                  Vander Planke, Miss. Augusta Maria  female  18.00      2      0              345764   18.0000              NaN        S
39            40         1       3                                                         Nicola-Yarred, Miss. Jamila  female  14.00      1      0                2651   11.2417              NaN        C
40            41         0       3                                      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.00      1      0                7546    9.4750              NaN        S
41            42         0       2                            Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)  female  27.00      1      0               11668   21.0000              NaN        S
42            43         0       3                                                                 Kraeff, Mr. Theodor    male    NaN      0      0              349253    7.8958              NaN        C
43            44         1       2                                            Laroche, Miss. Simonne Marie Anne Andree  female   3.00      1      2       SC/Paris 2123   41.5792              NaN        C
44            45         1       3                                                       Devaney, Miss. Margaret Delia  female  19.00      0      0              330958    7.8792              NaN        Q
45            46         0       3                                                            Rogers, Mr. William John    male    NaN      0      0     S.C./A.4. 23567    8.0500              NaN        S
46            47         0       3                                                                   Lennon, Mr. Denis    male    NaN      1      0              370371   15.5000              NaN        Q
47            48         1       3                                                           O'Driscoll, Miss. Bridget  female    NaN      0      0               14311    7.7500              NaN        Q
48            49         0       3                                                                 Samaan, Mr. Youssef    male    NaN      2      0                2662   21.6792              NaN        C
49            50         0       3                                       Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.00      1      0              349237   17.8000              NaN        S
50            51         0       3                                                          Panula, Master. Juha Niilo    male   7.00      4      1             3101295   39.6875              NaN        S
51            52         0       3                                                        Nosworthy, Mr. Richard Cater    male  21.00      0      0          A/4. 39886    7.8000              NaN        S
52            53         1       1                                            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.00      1      0            PC 17572   76.7292              D33        C
53            54         1       2                                  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)  female  29.00      1      0                2926   26.0000              NaN        S
54            55         0       1                                                      Ostby, Mr. Engelhart Cornelius    male  65.00      0      1              113509   61.9792              B30        C
55            56         1       1                                                                   Woolner, Mr. Hugh    male    NaN      0      0               19947   35.5000              C52        S
56            57         1       2                                                                   Rugg, Miss. Emily  female  21.00      0      0          C.A. 31026   10.5000              NaN        S
57            58         0       3                                                                 Novel, Mr. Mansouer    male  28.50      0      0                2697    7.2292              NaN        C
58            59         1       2                                                        West, Miss. Constance Mirium  female   5.00      1      2          C.A. 34651   27.7500              NaN        S
59            60         0       3                                                  Goodwin, Master. William Frederick    male  11.00      5      2             CA 2144   46.9000              NaN        S
60            61         0       3                                                               Sirayanian, Mr. Orsen    male  22.00      0      0                2669    7.2292              NaN        C
61            62         1       1                                                                 Icard, Miss. Amelie  female  38.00      0      0              113572   80.0000              B28      NaN
62            63         0       1                                                         Harris, Mr. Henry Birkhardt    male  45.00      1      0               36973   83.4750              C83        S
63            64         0       3                                                               Skoog, Master. Harald    male   4.00      3      2              347088   27.9000              NaN        S
64            65         0       1                                                               Stewart, Mr. Albert A    male    NaN      0      0            PC 17605   27.7208              NaN        C
65            66         1       3                                                            Moubarek, Master. Gerios    male    NaN      1      1                2661   15.2458              NaN        C
66            67         1       2                                                        Nye, Mrs. (Elizabeth Ramell)  female  29.00      0      0          C.A. 29395   10.5000              F33        S
67            68         0       3                                                            Crease, Mr. Ernest James    male  19.00      0      0           S.P. 3464    8.1583              NaN        S
68            69         1       3                                                     Andersson, Miss. Erna Alexandra  female  17.00      4      2             3101281    7.9250              NaN        S
69            70         0       3                                                                   Kink, Mr. Vincenz    male  26.00      2      0              315151    8.6625              NaN        S
70            71         0       2                                                          Jenkin, Mr. Stephen Curnow    male  32.00      0      0          C.A. 33111   10.5000              NaN        S
71            72         0       3                                                          Goodwin, Miss. Lillian Amy  female  16.00      5      2             CA 2144   46.9000              NaN        S
72            73         0       2                                                                Hood, Mr. Ambrose Jr    male  21.00      0      0        S.O.C. 14879   73.5000              NaN        S
73            74         0       3                                                         Chronopoulos, Mr. Apostolos    male  26.00      1      0                2680   14.4542              NaN        C
74            75         1       3                                                                       Bing, Mr. Lee    male  32.00      0      0                1601   56.4958              NaN        S
75            76         0       3                                                             Moen, Mr. Sigurd Hansen    male  25.00      0      0              348123    7.6500            F G73        S
76            77         0       3                                                                   Staneff, Mr. Ivan    male    NaN      0      0              349208    7.8958              NaN        S
77            78         0       3                                                            Moutal, Mr. Rahamin Haim    male    NaN      0      0              374746    8.0500              NaN        S
78            79         1       2                                                       Caldwell, Master. Alden Gates    male   0.83      0      2              248738   29.0000              NaN        S
79            80         1       3                                                            Dowdell, Miss. Elizabeth  female  30.00      0      0              364516   12.4750              NaN        S
80            81         0       3                                                                Waelens, Mr. Achille    male  22.00      0      0              345767    9.0000              NaN        S
81            82         1       3                                                         Sheerlinck, Mr. Jan Baptist    male  29.00      0      0              345779    9.5000              NaN        S
82            83         1       3                                                      McDermott, Miss. Brigdet Delia  female    NaN      0      0              330932    7.7875              NaN        Q
83            84         0       1                                                             Carrau, Mr. Francisco M    male  28.00      0      0              113059   47.1000              NaN        S
84            85         1       2                                                                 Ilett, Miss. Bertha  female  17.00      0      0          SO/C 14885   10.5000              NaN        S
85            86         1       3                             Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)  female  33.00      3      0             3101278   15.8500              NaN        S
86            87         0       3                                                              Ford, Mr. William Neal    male  16.00      1      3          W./C. 6608   34.3750              NaN        S
87            88         0       3                                                       Slocovski, Mr. Selman Francis    male    NaN      0      0     SOTON/OQ 392086    8.0500              NaN        S
88            89         1       1                                                          Fortune, Miss. Mabel Helen  female  23.00      3      2               19950  263.0000      C23 C25 C27        S
89            90         0       3                                                              Celotti, Mr. Francesco    male  24.00      0      0              343275    8.0500              NaN        S
90            91         0       3                                                                Christmann, Mr. Emil    male  29.00      0      0              343276    8.0500              NaN        S
91            92         0       3                                                          Andreasson, Mr. Paul Edvin    male  20.00      0      0              347466    7.8542              NaN        S
92            93         0       1                                                         Chaffee, Mr. Herbert Fuller    male  46.00      1      0         W.E.P. 5734   61.1750              E31        S
93            94         0       3                                                             Dean, Mr. Bertram Frank    male  26.00      1      2           C.A. 2315   20.5750              NaN        S
94            95         0       3                                                                   Coxon, Mr. Daniel    male  59.00      0      0              364500    7.2500              NaN        S
95            96         0       3                                                         Shorney, Mr. Charles Joseph    male    NaN      0      0              374910    8.0500              NaN        S
96            97         0       1                                                           Goldschmidt, Mr. George B    male  71.00      0      0            PC 17754   34.6542               A5        C

In [43]:
var1=pd.get_dummies(df,columns=['Sex'],dtype='int')
X = var1.drop(columns=['Name','PassengerId','Pclass','Age','Ticket','Cabin','Embarked','Survived'])
Y = var1[['Survived']]
print(X.to_string())

     SibSp  Parch      Fare  Sex_female  Sex_male
0        1      0    7.2500           0         1
1        1      0   71.2833           1         0
2        0      0    7.9250           1         0
3        1      0   53.1000           1         0
4        0      0    8.0500           0         1
5        0      0    8.4583           0         1
6        0      0   51.8625           0         1
7        3      1   21.0750           0         1
8        0      2   11.1333           1         0
9        1      0   30.0708           1         0
10       1      1   16.7000           1         0
11       0      0   26.5500           1         0
12       0      0    8.0500           0         1
13       1      5   31.2750           0         1
14       0      0    7.8542           1         0
15       0      0   16.0000           1         0
16       4      1   29.1250           0         1
17       0      0   13.0000           0         1
18       1      0   18.0000           1         0
19       0      0    7.2250           1         0
20       0      0   26.0000           0         1
21       0      0   13.0000           0         1
22       0      0    8.0292           1         0
23       0      0   35.5000           0         1
24       3      1   21.0750           1         0
25       1      5   31.3875           1         0
26       0      0    7.2250           0         1
27       3      2  263.0000           0         1
28       0      0    7.8792           1         0
29       0      0    7.8958           0         1
30       0      0   27.7208           0         1
31       1      0  146.5208           1         0
32       0      0    7.7500           1         0
33       0      0   10.5000           0         1
34       1      0   82.1708           0         1
35       1      0   52.0000           0         1
36       0      0    7.2292           0         1
37       0      0    8.0500           0         1
38       2      0   18.0000           1         0
39       1      0   11.2417           1         0
40       1      0    9.4750           1         0
41       1      0   21.0000           1         0
42       0      0    7.8958           0         1
43       1      2   41.5792           1         0
44       0      0    7.8792           1         0
45       0      0    8.0500           0         1
46       1      0   15.5000           0         1
47       0      0    7.7500           1         0
48       2      0   21.6792           0         1
49       1      0   17.8000           1         0
50       4      1   39.6875           0         1
51       0      0    7.8000           0         1
52       1      0   76.7292           1         0
53       1      0   26.0000           1         0
54       0      1   61.9792           0         1
55       0      0   35.5000           0         1
56       0      0   10.5000           1         0
57       0      0    7.2292           0         1
58       1      2   27.7500           1         0
59       5      2   46.9000           0         1
60       0      0    7.2292           0         1
61       0      0   80.0000           1         0
62       1      0   83.4750           0         1
63       3      2   27.9000           0         1
64       0      0   27.7208           0         1
65       1      1   15.2458           0         1
66       0      0   10.5000           1         0
67       0      0    8.1583           0         1
68       4      2    7.9250           1         0
69       2      0    8.6625           0         1
70       0      0   10.5000           0         1
71       5      2   46.9000           1         0
72       0      0   73.5000           0         1
73       1      0   14.4542           0         1
74       0      0   56.4958           0         1
75       0      0    7.6500           0         1
76       0      0    7.8958           0         1
77       0      0    8.0500           0         1
78       0      2   29.0000           0         1
79       0      0   12.4750           1         0
80       0      0    9.0000           0         1
81       0      0    9.5000           0         1
82       0      0    7.7875           1         0
83       0      0   47.1000           0         1
84       0      0   10.5000           1         0
85       3      0   15.8500           1         0
86       1      3   34.3750           0         1
87       0      0    8.0500           0         1
88       3      2  263.0000           1         0
89       0      0    8.0500           0         1
90       0      0    8.0500           0         1
91       0      0    7.8542           0         1
92       1      0   61.1750           0         1
93       1      2   20.5750           0         1
94       0      0    7.2500           0         1
95       0      0    8.0500           0         1
96       0      0   34.6542           0         1
97       0      1   63.3583           0         1
98       0      1   23.0000           1         0
99       1      0   26.0000           0         1
100      0      0    7.8958           1         0
101      0      0    7.8958           0         1
102      0      1   77.2875           0         1
103      0      0    8.6542           0         1
104      2      0    7.9250           0         1
105      0      0    7.8958           0         1
106      0      0    7.6500           1         0
107      0      0    7.7750           0         1
108      0      0    7.8958           0         1
109      1      0   24.1500           1         0
110      0      0   52.0000           0         1
111      1      0   14.4542           1         0
112      0      0    8.0500           0         1
113      1      0    9.8250           1         0
114      0      0   14.4583           1         0
115      0      0    7.9250           0         1
116      0      0    7.7500           0         1
117      1      0   21.0000           0         1
118      0      1  247.5208           0         1
119      4      2   31.2750           1         0
120      2      0   73.5000           0         1
121      0      0    8.0500           0         1
122      1      0   30.0708           0         1
123      0      0   13.0000           1         0
124      0      1   77.2875           0         1
125      1      0   11.2417           0         1
126      0      0    7.7500           0         1
127      0      0    7.1417           0         1
128      1      1   22.3583           1         0
129      0      0    6.9750           0         1
130      0      0    7.8958           0         1
131      0      0    7.0500           0         1
132      1      0   14.5000           1         0
133      1      0   26.0000           1         0
134      0      0   13.0000           0         1
135      0      0   15.0458           0         1
136      0      2   26.2833           1         0
137      1      0   53.1000           0         1
138      0      0    9.2167           0         1
139      0      0   79.2000           0         1
140      0      2   15.2458           1         0
141      0      0    7.7500           1         0
142      1      0   15.8500           1         0
143      0      0    6.7500           0         1
144      0      0   11.5000           0         1
145      1      1   36.7500           0         1
146      0      0    7.7958           0         1
147      2      2   34.3750           1         0
148      0      2   26.0000           0         1
149      0      0   13.0000           0         1
150      0      0   12.5250           0         1
151      1      0   66.6000           1         0
152      0      0    8.0500           0         1
153      0      2   14.5000           0         1
154      0      0    7.3125           0         1
155      0      1   61.3792           0         1
156      0      0    7.7333           1         0
157      0      0    8.0500           0         1
158      0      0    8.6625           0         1
159      8      2   69.5500           0         1
160      0      1   16.1000           0         1
161      0      0   15.7500           1         0
162      0      0    7.7750           0         1
163      0      0    8.6625           0         1
164      4      1   39.6875           0         1
165      0      2   20.5250           0         1
166      0      1   55.0000           1         0
167      1      4   27.9000           1         0
168      0      0   25.9250           0         1
169      0      0   56.4958           0         1
170      0      0   33.5000           0         1
171      4      1   29.1250           0         1
172      1      1   11.1333           1         0
173      0      0    7.9250           0         1
174      0      0   30.6958           0         1
175      1      1    7.8542           0         1
176      3      1   25.4667           0         1
177      0      0   28.7125           1         0
178      0      0   13.0000           0         1
179      0      0    0.0000           0         1
180      8      2   69.5500           1         0
181      0      0   15.0500           0         1
182      4      2   31.3875           0         1
183      2      1   39.0000           0         1
184      0      2   22.0250           1         0
185      0      0   50.0000           0         1
186      1      0   15.5000           1         0
187      0      0   26.5500           0         1
188      1      1   15.5000           0         1
189      0      0    7.8958           0         1
190      0      0   13.0000           1         0
191      0      0   13.0000           0         1
192      1      0    7.8542           1         0
193      1      1   26.0000           0         1
194      0      0   27.7208           1         0
195      0      0  146.5208           1         0
196      0      0    7.7500           0         1
197      0      1    8.4042           0         1
198      0      0    7.7500           1         0
199      0      0   13.0000           1         0
200      0      0    9.5000           0         1
201      8      2   69.5500           0         1
202      0      0    6.4958           0         1
203      0      0    7.2250           0         1
204      0      0    8.0500           0         1
205      0      1   10.4625           1         0
206      1      0   15.8500           0         1
207      0      0   18.7875           0         1
208      0      0    7.7500           1         0
209      0      0   31.0000           0         1
210      0      0    7.0500           0         1
211      0      0   21.0000           1         0
212      0      0    7.2500           0         1
213      0      0   13.0000           0         1
214      1      0    7.7500           0         1
215      1      0  113.2750           1         0
216      0      0    7.9250           1         0
217      1      0   27.0000           0         1
218      0      0   76.2917           1         0
219      0      0   10.5000           0         1
220      0      0    8.0500           0         1
221      0      0   13.0000           0         1
222      0      0    8.0500           0         1
223      0      0    7.8958           0         1
224      1      0   90.0000           0         1
225      0      0    9.3500           0         1
226      0      0   10.5000           0         1
227      0      0    7.2500           0         1
228      0      0   13.0000           0         1
229      3      1   25.4667           1         0
230      1      0   83.4750           1         0
231      0      0    7.7750           0         1
232      0      0   13.5000           0         1
233      4      2   31.3875           1         0
234      0      0   10.5000           0         1
235      0      0    7.5500           1         0
236      1      0   26.0000           0         1
237      0      2   26.2500           1         0
238      0      0   10.5000           0         1
239      0      0   12.2750           0         1
240      1      0   14.4542           1         0
241      1      0   15.5000           1         0
242      0      0   10.5000           0         1
243      0      0    7.1250           0         1
244      0      0    7.2250           0         1
245      2      0   90.0000           0         1
246      0      0    7.7750           1         0
247      0      2   14.5000           1         0
248      1      1   52.5542           0         1
249      1      0   26.0000           0         1
250      0      0    7.2500           0         1
251      1      1   10.4625           1         0
252      0      0   26.5500           0         1
253      1      0   16.1000           0         1
254      0      2   20.2125           1         0
255      0      2   15.2458           1         0
256      0      0   79.2000           1         0
257      0      0   86.5000           1         0
258      0      0  512.3292           1         0
259      0      1   26.0000           1         0
260      0      0    7.7500           0         1
261      4      2   31.3875           0         1
262      1      1   79.6500           0         1
263      0      0    0.0000           0         1
264      0      0    7.7500           1         0
265      0      0   10.5000           0         1
266      4      1   39.6875           0         1
267      1      0    7.7750           0         1
268      0      1  153.4625           1         0
269      0      0  135.6333           1         0
270      0      0   31.0000           0         1
271      0      0    0.0000           0         1
272      0      1   19.5000           1         0
273      0      1   29.7000           0         1
274      0      0    7.7500           1         0
275      1      0   77.9583           1         0
276      0      0    7.7500           1         0
277      0      0    0.0000           0         1
278      4      1   29.1250           0         1
279      1      1   20.2500           1         0
280      0      0    7.7500           0         1
281      0      0    7.8542           0         1
282      0      0    9.5000           0         1
283      0      0    8.0500           0         1
284      0      0   26.0000           0         1
285      0      0    8.6625           0         1
286      0      0    9.5000           0         1
287      0      0    7.8958           0         1
288      0      0   13.0000           0         1
289      0      0    7.7500           1         0
290      0      0   78.8500           1         0
291      1      0   91.0792           1         0
292      0      0   12.8750           0         1
293      0      0    8.8500           1         0
294      0      0    7.8958           0         1
295      0      0   27.7208           0         1
296      0      0    7.2292           0         1
297      1      2  151.5500           1         0
298      0      0   30.5000           0         1
299      0      1  247.5208           1         0
300      0      0    7.7500           1         0
301      2      0   23.2500           0         1
302      0      0    0.0000           0         1
303      0      0   12.3500           1         0
304      0      0    8.0500           0         1
305      1      2  151.5500           0         1
306      0      0  110.8833           1         0
307      1      0  108.9000           1         0
308      1      0   24.0000           0         1
309      0      0   56.9292           1         0
310      0      0   83.1583           1         0
311      2      2  262.3750           1         0
312      1      1   26.0000           1         0
313      0      0    7.8958           0         1
314      1      1   26.2500           0         1
315      0      0    7.8542           1         0
316      1      0   26.0000           1         0
317      0      0   14.0000           0         1
318      0      2  164.8667           1         0
319      1      1  134.5000           1         0
320      0      0    7.2500           0         1
321      0      0    7.8958           0         1
322      0      0   12.3500           1         0
323      1      1   29.0000           1         0
324      8      2   69.5500           0         1
325      0      0  135.6333           1         0
326      0      0    6.2375           0         1
327      0      0   13.0000           1         0
328      1      1   20.5250           1         0
329      0      1   57.9792           1         0
330      2      0   23.2500           1         0
331      0      0   28.5000           0         1
332      0      1  153.4625           0         1
333      2      0   18.0000           0         1
334      1      0  133.6500           1         0
335      0      0    7.8958           0         1
336      1      0   66.6000           0         1
337      0      0  134.5000           1         0
338      0      0    8.0500           0         1
339      0      0   35.5000           0         1
340      1      1   26.0000           0         1
341      3      2  263.0000           1         0
342      0      0   13.0000           0         1
343      0      0   13.0000           0         1
344      0      0   13.0000           0         1
345      0      0   13.0000           1         0
346      0      0   13.0000           1         0
347      1      0   16.1000           1         0
348      1      1   15.9000           0         1
349      0      0    8.6625           0         1
350      0      0    9.2250           0         1
351      0      0   35.0000           0         1
352      1      1    7.2292           0         1
353      1      0   17.8000           0         1
354      0      0    7.2250           0         1
355      0      0    9.5000           0         1
356      0      1   55.0000           1         0
357      0      0   13.0000           1         0
358      0      0    7.8792           1         0
359      0      0    7.8792           1         0
360      1      4   27.9000           0         1
361      1      0   27.7208           0         1
362      0      1   14.4542           1         0
363      0      0    7.0500           0         1
364      1      0   15.5000           0         1
365      0      0    7.2500           0         1
366      1      0   75.2500           1         0
367      0      0    7.2292           1         0
368      0      0    7.7500           1         0
369      0      0   69.3000           1         0
370      1      0   55.4417           0         1
371      1      0    6.4958           0         1
372      0      0    8.0500           0         1
373      0      0  135.6333           0         1
374      3      1   21.0750           1         0
375      1      0   82.1708           1         0
376      0      0    7.2500           1         0
377      0      2  211.5000           0         1
378      0      0    4.0125           0         1
379      0      0    7.7750           0         1
380      0      0  227.5250           1         0
381      0      2   15.7417           1         0
382      0      0    7.9250           0         1
383      1      0   52.0000           1         0
384      0      0    7.8958           0         1
385      0      0   73.5000           0         1
386      5      2   46.9000           0         1
387      0      0   13.0000           1         0
388      0      0    7.7292           0         1
389      0      0   12.0000           1         0
390      1      2  120.0000           0         1
391      0      0    7.7958           0         1
392      2      0    7.9250           0         1
393      1      0  113.2750           1         0
394      0      2   16.7000           1         0
395      0      0    7.7958           0         1
396      0      0    7.8542           1         0
397      0      0   26.0000           0         1
398      0      0   10.5000           0         1

In [44]:
import sklearn.model_selection
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.16)
print(f"X_train = {x_train.shape}\nX_test = {x_test.shape}\nY_train = {y_train.shape}\nY_test = {y_test.shape}")

X_train = (748, 5)
X_test = (143, 5)
Y_train = (748, 1)
Y_test = (143, 1)

In [45]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train.values,y_train.values)

LogisticRegression()

In [46]:
model.score(x_train.values,y_train.values)

0.7927807486631016

In [48]:
r=model.predict([[1,0,1.2500,1,0]])
print(r)

[1]

In [71]:
count = int(input("Enter number of persons :"))

for i in range(count):
    sib=int(input("Enter SibSP value : "))
    parch=int(input("Enter Parch value :"))
    fare=float(input("Enter Fare :"))
    sexm=int(input("Enter gender :"))
    sexf=int(input())
    answer=model.predict([[sib,parch,fare,sexm,sexf]])
for i in answer:
    if answer[0]:
        print("Unfortunately , Not Survived !")
    else:
        print("Bro survived !! ")

Bro survived !!